project:
  output-dir: "docs-manual"
book:
  chapters:
    - index.qmd
    - part: "Overviews"
      chapters:
      - overviews/intro.qmd
      - overviews/program.qmd
    - part: "Projects"
      chapters:
      - projects/creating-a-new-project.qmd
      - projects/reviewing-standard-projects.qmd
      - projects/reviewing-batch-project.qmd
      - projects/customizing-results.qmd
      - projects/publishing.qmd
    - part: "Options & Features"
      chapters:
      - options/program-options.qmd
      - options/additional-features.qmd
    - part: "Readability Tests"
      chapters:
      - readability-tests-english.qmd
      - readability-tests-spanish.qmd
      - readability-tests-german.qmd
      - custom-tests-and-bundles.qmd
    - part: "Examples"
      chapters:
      - examples/examples-getting-started.qmd
      - examples/examples-advanced.qmd
      - examples/examples-editing.qmd
      - examples/examples-graphs.qmd
      - examples/examples-batch-projects.qmd
      - examples/examples-creating-custom-tests.qmd
    - part: "Notes"
      chapters:
      - analysis-notes.qmd
      - scoring-notes.qmd
  appendices:
    - acknowledgements/intro.qmd
    - glossary/shortcuts.qmd
    - glossary/glossary.qmd