# Documentation

## Style

The following styles should be applied to all help projects:

- Software and library names should be italicized.
- References to dialog/menu/button/tab names should be bolded.
- File names and paths should be bolded.
- Data types (programming docs) should be in typewriter font.
- Parameters to functions (programming docs) should be italicized.
- Values (numbers and strings) in programming docs should be in typewriter font.
- Values elsewhere:
 - Numbers should not be formatted.
 - Strings and single characters should be italicized (quoting them makes them difficult to read).

## Editing

The documentation is stored in **quarto** projects in the **readability-studio-manual** and **readability-studio-api** folders.

## Screenshots {#creating-screenshots}

### Generating Screenshots {-}

To generate screenshots, do the following:

- Run the script **docs/generate-screenshots.lua** from *Readability Studio*

This will generate all new screenshots in the root **docs/readability-studio-manual/images**.
The subdirectory **non-generated** will not be effected, but does not need to be.
It should not contain images effected by the program's UI changes and should not contain images with content that should be localized.

### Reviewing Screenshots {-}

After generating new screenshots, [build](#building-help) the help and review the following topics to verify that the values referenced in the screenshots match the help:

- **reviewing-readability-graphs.html**
- **reviewing-statistics.html**
- **reviewing-batch-scores.html**
- **reviewing-batch-box-plots.html**
- **reviewing-batch-histograms.html**
- **searching-for-overly-long-sentences.html**
- **reviewing-dolch.html**
- **analyzing-a-work-in-progress.html**
- **reviewing-a-collection-of-documents.html**
- **excluding-text-from-analysis.html**
- **creating-a-custom-index-test.html**
- **finding-difficult-sections.html**

## Building {#building-help}

Run **docs/build-help-projects.R** to build all help projects. This should install all needed *R* and *LaTeX* packages the first time you run it.
If there are any errors while installing the *LaTeX* packages,
run the script again; you may experience connection issues to *ctan* and re-running the script will fix it.
