{{< pagebreak >}}
## `ExportFilteredText` {#standard-exportfilteredtext}

Saves a copy of the project's document with excluded text (and other optional items) filtered out. Returns `true` if successful.

### Syntax {-}

``` {.lua}
ExportFilteredText(string outputFilePath,
                   boolean romanizeText,
                   boolean removeEllipses,
                   boolean removeBullets,
                   boolean removeFilePaths,
                   boolean stripAbbreviations)
```

### Parameters {-}

**Parameter** | **Description**
| :-- | :-- |
| `string` outputFilePath | The folder to save the filtered document. |
| `boolean` romanizeText | Whether to converted extended ASCII characters to simpler versions (e.g., replacing smart quotes with straight quotes). |
| `boolean` removeEllipses | Whether to remove ellipses. |
| `boolean` removeBullets | Whether to remove bullets. |
| `boolean` removeFilePaths | Whether to remove filepaths. |
| `boolean` stripAbbreviations | Whether to remove the trailing periods off of abbreviations. |

::: {.notesection data-latex=""}
This is useful for transforming a document to be analyzed by other software that may have difficulty with abbreviations with periods, accented characters, etc. 
:::
