## `SetGrammarResultsOptions`

Sets which grammar results should be included for new projects.

### Syntax {-}

``` {.lua}
SetGrammarResultsOptions(boolean includeHighlightedReport,
                         boolean includeErrors,
                         boolean includePossibleMisspellings,
                         boolean includeRepeatedWords,
                         boolean includeArticleMismatches,
                         boolean includeRedundantPhrases,
                         boolean includeOverusedWords,
                         boolean includeWordiness,
                         boolean includeCliches,
                         boolean includePassiveVoice,
                         boolean includeConjunctionStartingSentences,
                         boolean includeLowercasedSentences)
```

### Parameters {-}

**Parameter** | **Description**
| :-- | :-- |
|`boolean` includeHighlightedReport | `true` to include the highlighted grammar report. | 
|`boolean` includeErrors | `true` to include wording errors and known misspellings. | 
|`boolean` includePossibleMisspellings | `true` to include possible misspellings. | 
|`boolean` includeRepeatedWords | `true` to include repeated words. | 
|`boolean` includeArticleMismatches | `true` to include article mismatches. | 
|`boolean` includeRedundantPhrases | `true` to include redundant phrases. | 
|`boolean` includeOverusedWords | `true` to include overused words. | 
|`boolean` includeWordiness | `true` to include wordiness. | 
|`boolean` includeCliches | `true` to include cliches. | 
|`boolean` includePassiveVoice | `true` to include passive voice. | 
|`boolean` includeConjunctionStartingSentences | `true` to include sentences that start with conjunctions. | 
|`boolean` includeLowercasedSentences | `true` to include sentences that start with lowercase letters. |

{{< pagebreak >}}