## New Fog Count\index{New Fog Count|ii} {#new-fog-count-test}

The New Fog Count\index{Gunning Fog!variations!New Fog Count} readability formula is Kincaid et al.'s modified version of the [Gunning Fog](#gunning-fog-test) Index [-@{kincaid-fishburne-rogers-chissom:1975}14] that was recalculated "to be more suitable for Navy use" [@{kincaid-fishburne-rogers-chissom:1975}11]; hence, it is designed for technical documents and manuals. This test calculates the grade level of a document based on sentence length and number of words containing three or more syllables.

This test was trained against reading-test results from 531 U.S. Navy personnel from four Naval technical training schools. Using these results, the following multiple regression equation was derived:

```{definition, newfogcount, name="New Fog Count formula"}
$$
G = (((Z + (3*F)) / S ) - 3) / 2
$$
```

Where:

+:----+:------------------------+
| G   | Grade level             |
+-----+-------------------------+
| F   | Number of complex words |
+-----+-------------------------+
| Z   | Number of easy words    |
+-----+-------------------------+
| S   | Number of sentences     |
+-----+-------------------------+

::: {.notesection data-latex=""}
This test uses the same easy-word and sentence counting methods as the [Gunning Fog](#gunning-fog-test) test.
:::

\newpage
