## (Powers-Sumner-Kearl) Gunning Fog\index{Powers-Sumner-Kearl!recalculated tests!Gunning Fog|(} {#psk-fog}

The (Powers-Sumner-Kearl) Gunning Fog readability formula (99–105) calculates the grade level of a document based on sentence length and number of syllables.

The goal of Powers, Sumner, and Kearl was to develop updated versions of four popular readability formulas: Dale-Chall, Flesch, Gunning Fog\index{Gunning Fog!Powers-Sumner-Kearl recalculation}, and Farr-Jenkins-Paterson. These updated formulas would be based on the newer (1950) edition of the McCall-Crabbs test criterion. By using this revised test material, Powers, Sumner, and Kearl aimed to “modernize the formulas by taking advantage of the more recently administered tests” and to “establish formulas which are derived from identical materials” (Powers, Sumner, and Kearl 100).

The training materials used to build the regression formulas were 383 prose passages from the 1950 edition of McCall-Crabbs's *Standard Test Lessons in Reading*. For validation, the formulas were tested against 113 samples from “various publications” (Powers, Sumner, and Kearl 100). Their results (shown below) implied somewhat strong correlations for their Dale-Chall and Flesch formulas and mild correlations for their FJP and Gunning Fog formulas:

- recalculated Dale-Chall: $r^2 = 0.5092$
- recalculated Flesch: $r^2 = 0.4034$
- recalculated Gunning Fog: $r^2 = 0.3440$
- recalculated Farr-Jenkins-Paterson: $r^2 = 0.3407$

The recalculated Gunning Fog formula is as follows:

```{definition, pskfog, name="(PSK) Gunning Fog formula"}
\begin{align*}
  G = & 3.0680 + (.0877*(W/S)) + \\
      & (.0984*((F/W)*100))
\end{align*}
```

Where:

+:----+:------------------------+
| G   | Grade level             |
+-----+-------------------------+
| W   | Number of words         |
+-----+-------------------------+
| F   | Number of complex words |
+-----+-------------------------+
| S   | Number of sentences     |
+-----+-------------------------+

::: {.notesection data-latex=""}
This test uses the same easy-word and sentence counting methods as the [Gunning Fog](#gunning-fog-test) test.
:::

\index{Powers-Sumner-Kearl!recalculated tests!Gunning Fog|)}

\newpage
