```{r}
#| include: false
#| eval: true

source('R/appdown.r')
```

# Linux `r os_logo('linux')`

| Install the following tools to build *{{< var PROGRAM_NAME >}}* |
| :-- |
| *GCC* {{< var MIN_GCC_REQUIRED >}} or higher (C++ and fortran compilers) |
| *CMake* {{< var CMAKE_MINIMUM_REQUIRED_VERSION >}} or higher |
| *git* |
| *AppImage* |
| *linuxdeploy* |
| *R* (optional) |
| *Quarto* (optional) |
| *POEdit* (optional) |

| Install the following libraries (and their development files, if mentioned) |
| :-- |
| *GTK 3*, *gtk3-devel*/*libgtk3-dev* |
| *libCURL*, *libcurl-devel*/*libcurl-dev* |
| *GStreamer*, *gstreamer-devel* |
| *libsecret*, *libsecret-devel*/*libsecret-1-dev* |
| *libwebkit2*, *libwebkit2-devel* |
| *SDL2-devel* |
| *libnotify*, *libnotify-devel*/*libnotify-dev* |
| *TBB*, *tbb-devel*/*tbb-dev* |
| *OpenMP* |
| *libopenssl*, *libopenssl-3-devel*/*libssl-dev* |
| *libxml2*, *libxml2-devel*/*libxml2-dev* |
| *libpoppler-cpp-dev* (optional |

If building the documentation, prepare *R* to install packages:

```{.bash}
R
install.packages("pacman")
```

{{< pagebreak >}}

## Download *wxWidgets* {-}

```{.bash}
git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules
```

This should be cloned into a folder next to *{{< var PROGRAM_NAME >}}*.

## Build *{{< var PROGRAM_NAME >}}* {-}

```{.bash include="build-commands.txt" start-line=1 end-line=7}
```

## Build the AppImage {-}

```{.bash}
linuxdeploy-x86_64.AppImage --appdir installers/unix/AppDir \
  --executable installers/unix/AppDir/usr/bin/readstudio \
  -d installers/unix/AppDir/readstudio.desktop \
  -i installers/unix/AppDir/app-logo.svg \
  --output appimage
mv Readability_Studio*.AppImage ./installers/unix
```

Once built, the AppImage will be available in `r menu(c('installers', 'unix'))`.
Apply a GPG signature to it before distributing.
