```{r}
#| include: false
#| eval: true

source('R/appdown.r')
```

# Microsoft^®^ Windows `r os_logo('Windows')`

| Requirements |
| :-- |
| 64-bit Windows {{< var WIN32_REQUIRED >}} (or higher) |
| x86_64 processor |
| {{< var MIN_RAM >}} of RAM ({{< var RAM_RECOMMENDED >}} recommended) |

The *Microsoft Visual C++ runtime* is also required.
This is normally managed via *Windows Update*, but can also be installed manually.
To install, download and run the latest [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) installer.

## Installing {-}

Run the installer ("rssetup{{< var FULL_VERSION >}}.exe") as an administrator.
You will be prompted for a user name, where to install the program, and which components to install.
After answering these prompts, continue the installer to completion.

## Uninstalling {-}

The program can be uninstalled via the system's **Apps & features** panel or from the command line.

In the installation folder of *{{< var PROGRAM_NAME >}}*, there will be file named similar to "unins???.exe."
System Admins can run this program remotely to uninstall the program from workstations.

::: {.tipsection data-latex=""}
"unins???.exe" can take parameters, such as `/VERYSILENT`.
Refer to the end of this chapter.
:::

{{< pagebreak >}}

## Updating {-}

To upgrade an installation, run the installer ("rssetup{{< var FULL_VERSION >}}.exe") as an administrator and follow the prompts.
If there is a previous installation of *{{< var PROGRAM_NAME >}}*, then the installer will update it.

::: {.notesection data-latex=""}
If updating a 32-bit edition of *{{< var PROGRAM_NAME >}}* (version 2021 or earlier), you will first need to uninstall the program.
The 64-bit editions default to the 64-bit *Windows* program folder, while earlier editions where installed to the "Program Files (x86)" folder.
Uninstalling any 32-bit editions will ensure that you won't have multiple installations after updating.
:::

## Silent Mode {-}

The installer uses *Inno Setup*, which provides support for silent install.
(This applies to installing, uninstalling, and upgrading.)
To perform a silent install, pass the command line arguments `/SILENT` or `/VERYSILENT`.
For example, the following will run a silent install that will not restart the computer and write its progress to a log file:

```{.bash}
rssetup.exe /SILENT /NORESTART /LOG
```

Available command line options include:

| Option | Purpose |
| :--    | :--     |
| `/SILENT` | Skips user prompts, keeping the default options. |
| `/VERYSILENT` | Same as `/SILENT`, but also hides the installer's window. |
| `/LOG` | Log the installer's progress to a temp file. |
| `/LOG="filename"` | Same as `/LOG`, but writes to the provided filename. |
| `/NORESTART` | Do not reboot after installation, even if necessary. |
| `/CLOSEAPPLICATIONS` | (Updater only) Close *{{< var PROGRAM_NAME >}}* if open during the update. |
| `/DIR="c:\foldername"` | (Installer and updater only) Where to install (or update) the program. (This will override the default installation path.) |
