## Coleman-Liau\index{Coleman-Liau|(idxit} {#sec-coleman-liau-test}

The Coleman-Liau formula calculates the grade level and estimated cloze\index{cloze} score of a document based on sentence length and character count.

Coleman and Liau noted the difficulties of using computers to count syllables [-@{coleman-liau}283] for readability formulas. As a solution, they presented a new formula that used character counts as an alternative to syllable counting. This formula was derived from a regression equation trained on the 36 150-word passages from the Miller and Coleman cloze study [-@{miller-coleman}851]. During validation, the factors of sentences and characters per 100 words yielded a strong correlation of $r^2 = .92$ against Miller and Coleman’s cloze scores.

Coleman-Liau calculates the [predicted cloze](#sec-cloze) percentage with the following formula:

::: {.callout-note icon=false}
## Coleman-Liau formula

$$
E = (141.8401 - (.214590*R)) + (1.079812*S)
$$
:::

Then convert the cloze percentage into a grade level with the following formula:

::: {.callout-note icon=false appearance="simple" title=""}
$$
G = (-27.4004*(E/100)) + 23.06395
$$
:::

Where:

+:----+:-------------------------------------+
| E   | Estimated cloze %                    |
+-----+--------------------------------------+
| G   | Grade level                          |
+-----+--------------------------------------+
| R   | Number of characters (per 100 words) |
+-----+--------------------------------------+
| S   | Number of sentences (per 100 words)  |
+-----+--------------------------------------+

Though not explicitly mentioned in their article [@{coleman-liau}284], the estimated cloze % from the first equation must be converted to a fraction (i.e., divided by 100) to produce the expected results.
For this reason, "$(E/100)$" is shown in the second equation, rather than just "estimated cloze %" as it appears in the source article. As an example, an estimated cloze % of 51.3 should yield a grade level of 9:

$$
9 = (-27.4004*(51.3/100)) + 23.06395
$$
\index{Coleman-Liau|)}

\newpage