## Danielson-Bryan 1\index{Danielson-Bryan 1|(ii} {#sec-danielson-bryan-1}

Danielson-Bryan 1 [-@{danielson-bryan}206] is meant for student materials and calculates the grade level of a document based on sentence length and character count.

DB1 was designed to be a faster method (compared to [Farr-Jenkins-Paterson](#sec-farr-jenkins-paterson)\index{Farr-Jenkins-Paterson!compared to Danielson-Bryan}) of calculating readability scores on UNIVAC 1105 computers. Rather than counting syllables, DB1 counts characters and punctuation, which was simpler to analyze on computers of that era. This performance benefit is more of a historical reference now; modern computers can calculate syllable counts optimally.

This test was trained against 383 selections from the 1950 edition of McCall-Crabbs *Standard Test Lessons in Reading*. For validation, the derived formula had an $r^2 = 0.575$, similar to Farr-Jenkins-Paterson's $r^2 = 0.553$. This regression equation is as follows:

```{definition, db1, name="Danielson-Bryan 1 formula"}
$$
G = 1.0364*(RP/W) + .0194*(RP/S) - .6059
$$
```

Where:

```{r, echo=F}
db1Data <- tibble(col1 = c("G", "W", "RP", "S"),
                  col2 = markdown_to_kable_cell(c("Grade level",
                                    "Number of words (see below)",
                                    "Number of characters^a^",
                                    "Number of sentences")))

colnames(db1Data) <- rep('', ncol(db1Data))
kableExtra::kbl(db1Data, booktabs=T, centering=T, align='l',escape=F) %>%
  kableExtra::kable_classic(full_width=F) %>%
  column_spec(2, width='10cm') %>%
  footnote(alphabet = c("In this context, characters are letters, numbers, and punctuation (except for sentence-ending punctuation)"),
           threeparttable=T)
```

In the original article, the statistic of "number of spaces between words" is suggested, rather than explicitly saying "number of words." Logically, this should be the number of words minus 1. However, in the article's example, number of spaces between words is the same as number of words (even when there are dashes connecting words). It is therefore assumed that the authors' intention was to count the number of words using the following logic:

- Count the number of spaces.
- Treat dashes connecting words as spaces.
- Add 1, considering how there would be one less space than words.

For this reason, the *number of words* statistic is a more accurate description of what the authors intended.\index{Danielson-Bryan 1|)}

\newpage