## Farr-Jenkins-Paterson\index{Farr-Jenkins-Paterson|ii} {#farr-jenkins-paterson}

The Farr-Jenkins-Paterson\index{Flesch Reading Ease!variations!Farr-Jenkins-Paterson} readability formula [-@{farr-jenkins-paterson}333–37] calculates the [Flesch](#flesch-test) difficulty level of a document based on sentence length and number of monosyllabic words.

Farr-Jenkins-Paterson was designed as a simpler way to calculate a Flesch score because it uses monosyllabic word counting instead of counting all syllables.

This test was trained on 360 100-word samples, producing the following equation:

```{definition, fjp, name="Farr-Jenkins-Paterson formula"}
$$
I = -31.517 - (1.015*(W/S)) + (1.599*((M/W)*100))
$$
```

Where:

+:----+:-----------------------------+
| I   | Flesch index score           |
+-----+------------------------------+
| W   | Number of words              |
+-----+------------------------------+
| M   | Number of monosyllabic words |
+-----+------------------------------+
| S   | Number of sentences          |
+-----+------------------------------+

For validation, Flesch and FJP scores from the aforementioned samples were compared, with a significant correlation of $r = 0.93$.

\newpage
