## (Powers-Sumner-Kearl) Farr-Jenkins-Paterson\index{Powers-Sumner-Kearl!recalculated tests!Farr-Jenkins-Paterson|(} {-#sec-psk-farr-jenkins-paterson}

The (Powers-Sumner-Kearl) Farr-Jenkins-Paterson readability formula [-@{powers-sumner-kearl}99–105] calculates the grade level of a document based on sentence length and number of monosyllabic words.

The goal of Powers, Sumner, and Kearl was to develop updated versions of four popular readability formulas: Dale-Chall, Flesch, Gunning Fog, and Farr-Jenkins-Paterson\index{Farr-Jenkins-Paterson!Powers-Sumner-Kearl recalculation}. These updated formulas would be based on the 1950 edition of the McCall-Crabbs test criterion. By using this revised test material, Powers, Sumner, and Kearl aimed to "modernize the formulas by taking advantage of the more recently administered tests" and to "establish formulas which are derived from identical materials" [-@{powers-sumner-kearl}100].

The training materials used to build the regression formulas were 383 prose passages from the 1950 edition of McCall-Crabbs's *Standard Test Lessons in Reading*. For validation, the formulas were tested against 113 samples from "various publications" [-@{powers-sumner-kearl}100]. Their results (shown below) implied somewhat strong correlations for their Dale-Chall and Flesch formulas and mild correlations for their FJP and Gunning Fog formulas:

- recalculated Dale-Chall: $r^2 = 0.5092$
- recalculated Flesch: $r^2 = 0.4034$
- recalculated Gunning Fog: $r^2 = 0.3440$
- recalculated Farr-Jenkins-Paterson: $r^2 = 0.3407$

The recalculated Farr-Jenkins-Paterson formula is as follows:

(PSK) Farr-Jenkins-Paterson formula:

\begin{align*}
  G = & 8.4335 + (.0923*(W/S)) - \\
      & (.0648*((M/W)*100))
\end{align*}

Where:

+:----+:-----------------------------+
| G   | Grade level                  |
+-----+------------------------------+
| W   | Number of words              |
+-----+------------------------------+
| M   | Number of monosyllabic words |
+-----+------------------------------+
| S   | Number of sentences          |
+-----+------------------------------+

\index{Powers-Sumner-Kearl!recalculated tests!Farr-Jenkins-Paterson|)}

\newpage
