Name: "en"; MessagesFile: "compiler:Default.isl,messages\messagesEN.isl"
Name: "fr"; MessagesFile: "compiler:Languages\French.isl,messages\messagesFR.isl"
Name: "de"; MessagesFile: "compiler:Languages\German.isl,messages\messagesDE.isl"
Name: "es"; MessagesFile: "compiler:Languages\Spanish.isl,messages\messagesES.isl"
Name: "pt"; MessagesFile: "compiler:Languages\Portuguese.isl,messages\messagesPT.isl"
Name: "jp"; MessagesFile: "compiler:Languages\Japanese.isl,messages\messagesJP.isl"
Name: "ru"; MessagesFile: "compiler:Languages\Russian.isl,messages\messagesRU.isl"
