# Keyboard Shortcuts {.unnumbered}

<!-- no break spaces are to add blank lines between each row in the shortcuts table,
     making it easier to read.-->

::: {.minipage data-latex="{\textwidth}"}
Table: Application Shortcuts

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Open the help                           `r keys('F1')`

&nbsp;                                  &nbsp;

Enable verbose logging                  Hold down `r keys('Shift')` (`r os_logo('windows')`) or
                                        `r keys('\\shift')` (`r os_logo('apple')`)<br>\linebreak
                                        while the program loads
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Project Shortcuts

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Show/hide the sidebar                   `r keys('F2')`                                          

&nbsp;                                  &nbsp;

Show/hide the ribbon                    `r keys('F4')`

&nbsp;                                  &nbsp;

Reload the project                      `r keys('F5')`

&nbsp;                                  &nbsp;

Create a new project from the clipboard `r keys(c('Ctrl','V'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','V'))` (`r os_logo('apple')`) 

&nbsp;                                  &nbsp;

Save the project                        `r keys(c('Ctrl','S'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','S'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Print the active window                 `r keys(c('Ctrl','P'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','P'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Remove the selected test                `r keys(c('Ctrl', 'Del'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\backdel'))` (`r os_logo('apple')`)
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Graph Shortcuts

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Zoom in                                 `r keys('{+}')`                                     

&nbsp;                                  &nbsp;

Zoom out                                `r keys('-')`                                       

&nbsp;                                  &nbsp;

Reset zoom                              `r keys('*')`                                       
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Lists Shortcuts

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Remove selected item(s) from a list     `r keys('Del')` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys('\\backdel')` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Edit selected item in a list            `r keys('Ins')`                                      

&nbsp;                                  &nbsp;

Add a new item to a list                `r keys(c('Ctrl','Ins'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','Ins'))` (`r os_logo('apple')`)
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Embedded Document Editor Shortcuts

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Save back to the project                `r keys(c('Ctrl','S'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','S'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Cut selected text                       `r keys(c('Ctrl','X'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','X'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Paste text from the clipboard           `r keys(c('Ctrl','V'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','V'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Copy selected text                      `r keys(c('Ctrl','C'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','C'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Undo previous edit                      `r keys(c('Ctrl','Z'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','Z'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Redo previous edit                      `r keys(c('Ctrl','Y'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','Y'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Insert date                             `r keys(c('Ctrl',';'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd',';'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Insert time                             `r keys(c('Ctrl','Shift',';'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\shift',';'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Find                                    `r keys(c('Ctrl','F'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','F'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Find next                               `r keys('F3')`

&nbsp;                                  &nbsp;

Replace                                 `r keys(c('Ctrl','H'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','H'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Select all                              `r keys(c('Ctrl','A'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','A'))` (`r os_logo('apple')`)
------------------------------------------------------------------------------------------------
:::
