project:
  type: book
  output-dir: "docs"
toc: true
toc-depth: 2
biblio-title: References
bibliography: cites.bib
biblio-style: mla
link-citations: true
nocite: '@*'
csl: modern-language-association.csl
pdf-cover: "images/non-generated/cover.pdf"
pdf-cover-author-color: "255, 255, 255"
pdf-cover-font-color: "255, 255, 255"
pdf-cover-color: "80, 0, 0"
number-sections: true
crossref:
  chapters: true
book:
  title: "{{< var PROGRAM_NAME >}} {{< var VERSION >}}"
  subtitle: Programming Manual
  description: "{{< var PROGRAM_DESCRIPTION >}}"
  author: '{{< var PROGRAM_AUTHOR >}}'
  date: today
  date-format: long
  output-file: "readability-studio-api"
  language: en
  search: false
  cover-image: "images/cover.png"
  image: "images/cover.png"
  chapters:
    - index.qmd
    - libraries/debug-overview.qmd
    - enums.qmd
format:
  pdf:
    documentclass: LegrandOrangeBook
    template: latex/default.tex
    include-in-header: latex/preamble.tex
    latex-engine: xelatex
    keep-tex: true
    citation-package: biblatex
    lot: false
    code-block-bg: false
    linkcolor: black
    citecolor: black
  html:
    theme: cosmo
    html-math-method: katex
    css: style.css
    smooth-scroll: true
