::: {.minipage data-latex="{\textwidth}"}
## `SetGrammarResultsOptions`

Sets which grammar results should be included.

### Syntax {-}

``` {.lua}
SetGrammarResultsOptions(boolean includeHighlightedReport,
                         boolean includeErrors,
                         boolean includePossibleMisspellings,
                         boolean includeRepeatedWords,
                         boolean includeArticleMismatches,
                         boolean includeRedundantPhrases,
                         boolean includeOverusedWords,
                         boolean includeWordiness,
                         boolean includeCliches,
                         boolean includePassiveVoice,
                         boolean includeConjunctionStartingSentences,
                         boolean includeLowercasedSentences)
```

### Parameters {-}

**Parameter** | **Description**
| :-- | :-- |
| `boolean` includeHighlightedReport | (Optional) `true` to include the highlighted grammar report. | 
| `boolean` includeErrors | (Optional) `true` to include wording errors and known misspellings. | 
| `boolean` includePossibleMisspellings | (Optional) `true` to include possible misspellings. | 
| `boolean` includeRepeatedWords | (Optional) `true` to include repeated words. | 
| `boolean` includeArticleMismatches | (Optional) `true` to include article mismatches. | 
| `boolean` includeRedundantPhrases | (Optional) `true` to include redundant phrases. | 
| `boolean` includeOverusedWords | (Optional) `true` to include overused words. | 
| `boolean` includeWordiness |(Optional)  `true` to include wordiness. | 
| `boolean` includeCliches | (Optional) `true` to include cliches. | 
| `boolean` includePassiveVoice | (Optional) `true` to include passive voice. | 
| `boolean` includeConjunctionStartingSentences | (Optional) `true` to include sentences that start with conjunctions. | 
| `boolean` includeLowercasedSentences | (Optional) `true` to include sentences that start with lowercase letters. |

:::: {.tipsection data-latex=""}
This can be optimized by placing it in between calls to [`DelayReloading()`](#batch-delayreloading) and [`Reload()`](#batch-reload).
::::
:::
