name: test-clang-format
on: [push,pull_request]

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "src"
          exclude: "src/Wisteria-Dataviz src/tinyxml2 src/tinyexpr-plusplus src/OleanderStemmingLibrary src/lua src/Catch2 src/lua-scripting/luna.h"
          extensions: 'h,cpp'
          style: file
          clangFormatVersion: 20
