# This workflow checks out code and scans the content for offensive / exclusive terms.
# The scan will provide context on the found terms and alternatvies that can be
# used instead.

name: Inclusiveness Analyzer scan
on: [push, pull_request]

jobs:
  Inclusiveness-Analyzer-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inclusiveness Analyzer
      uses: microsoft/InclusivenessAnalyzer@v1.0.1
      with:
        excludeUnchangedFiles: false
        failOnNonInclusiveTerm: true
        excludeFiles: src/Catch2/*,src/tinyxml2/*,src/Wisteria-Dataviz/src/utfcpp/*,src/Wisteria-Dataviz/src/CRCpp/*,src/Wisteria-Dataviz/src/easyexif/*
        excludeTerms: he,she