name: quneiform
on: [push]

jobs:
  build:
    name: quneiform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: install quneiform
        run: |
             git clone https://github.com/eclipse-quneiform/quneiform.git --recurse-submodules
             cd quneiform
             cmake ./
             make -j4
             cd ..

      - name: analyze
        run: |
             ./quneiform/bin/quneiform ./src -q --ignore=Wisteria-Dataviz/demo/demo.cpp,Wisteria-Dataviz/src/base/version.h,Wisteria-Dataviz/src/math,Wisteria-Dataviz/src/debug,Wisteria-Dataviz/src/util/logfile.cpp,Wisteria-Dataviz/src/import/,Wisteria-Dataviz/tests,lua,Wisteria-Dataviz/src/base/colors.cpp,Wisteria-Dataviz/locale/es.po,readability,Catch2,OleanderStemmingLibrary,tinyexpr-plusplus,tinyxml2,Wisteria-Dataviz/src/utfcpp,Wisteria-Dataviz/src/easyexif,Wisteria-Dataviz/src/CRCpp,Wisteria-Dataviz/src/wxSimpleJSON --enable=allI18N,allCodeFormatting --disable=suspectL10NUsage -o i18nresults.txt
             cat i18nresults.txt
             
      - name: print output
        run: |
             REPORTFILE=./i18nresults.txt
             WARNINGSFILE=./warnings.txt
             if test -f "$REPORTFILE"; then
                cat "$REPORTFILE" > "$WARNINGSFILE"
                # are there any warnings?
                if grep -qP '\[[a-zA-Z0-9]+\]' "$WARNINGSFILE"; then
                    # print the remaining warnings
                    echo Warnings detected:
                    echo ==================
                    cat "$WARNINGSFILE" | grep -P '\[[a-zA-Z0-9]+\]'
                    # fail the job
                    exit 1
                else
                    echo No warnings detected
                fi
             else
                echo "$REPORTFILE" not found
             fi
