name: Spell Check
on: [push, pull_request]

jobs:
  check-unix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Check Spelling

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install codespell
        run: |
          pip install codespell
      - name: Run codespell
        run: |
          codespell src/ *.md *.rmd --skip="syllable.cpp,negating_word.cpp" -L forcast,ges,ded,sie,ure,nd,claus,compres,ue,oder,pard,als,atleast
          rc=$?
          if [ $rc != 0 ]; then
          cat <<EOF

          =================================== ERROR ===================================
          Spell check failed, please correct the spelling mistakes at the locations
          listed above. If any of the reported mistakes are false positives, please add
          the lines provoking them to misc/suppressions/codespell-lines file or, if
          there are many occurrences of the same word, add this word to codespell-words
          file in the same directory.
          EOF
          >& 2
              exit $rc
          fi
