name: Linux Unit Tests
on: [push]

jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: build & run tests
        run: |
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd ReadabilityStudio/tests
             cmake ./
             make -j4
             cd bin
             ./RSTestRunner > results.txt 2>&1
             cat results.txt
             ./RSTestRunner --reporter JUnit::out=rs-junit.xml
             errors=$(cat rs-junit.xml | grep -Po '(errors)="\K[^"]*')
             failures=$(cat rs-junit.xml | grep -Po '(failures)="\K[^"]*')
             if [ "$errors" -gt 0 ]; then
               echo "Error count is: ${errors}"
               exit 1
             fi
             if [ "$failures" -gt 0 ]; then
               echo "Failure count is: ${failures}"
               exit 1
             fi
