name: Linux Build
on: [push, pull_request]

jobs:
  build:
    name: ubuntu-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download wxWidgets
        run: |
             export DISPLAY=:0.0
             export DEBIAN_FRONTEND=noninteractive
             sudo apt-get update && sudo apt-get install xvfb cmake libtbb-dev libgtk-3-0 libgtk-3-dev libwebkit2gtk-4.1-0 libwebkit2gtk-4.1-dev libcurl4-openssl-dev
             git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules

      - name: Install LinuxDeploy
        id: install-linuxdeploy
        uses: miurahr/install-linuxdeploy-action@v1.8.0

      - name: Build
        run: |
             cmake . -DCMAKE_BUILD_TYPE=Release
             cmake --build . -j4 --config Release
             ${{ steps.install-linuxdeploy.outputs.linuxdeploy }} \
               --appdir installers/unix/AppDir \
               --executable installers/unix/AppDir/usr/bin/readstudio \
               -d installers/unix/AppDir/readstudio.desktop \
               -i installers/unix/AppDir/app-logo.svg \
               --output appimage
               mv Readability_Studio*.AppImage ./installers/unix

      - name: Archive AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Linux AppImage
          path: ${{ github.workspace }}/installers/unix/*.AppImage
